# This is a basic workflow to help you get started with Actions

name: Build and deploy production
on:
  workflow_dispatch:
   inputs:
      version:
        type: choice
        description: Version type
        options: 
        - patch
        - minor
        - major
      
env:
  node_version: 22
  deployment_branch: main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build-and-publish:
    permissions:
      contents: write
      packages: write
    uses: jpbnetley/npm-version-release-action/.github/workflows/action.yml@main
    with:
      node_version: 22
      package_manager: 'npm'
      path_to_package_json: './package.json'
      path_to_package_lock: './package-lock.json'
      registry_url: 'https://npm.pkg.github.com'
      install_command: 'npm ci'
      build_command: 'npm run build'
      build_output_path: 'dist'
      deployment_branch_name: 'main'
      version_command: 'npm run version:${{ github.event.inputs.version }}'
      publish_command: 'npm run version:publish'
    secrets: inherit
