# This is a basic workflow to help you get started with Actions

name: Build and deploy production
on:
  workflow_dispatch:
   inputs:
      version:
        type: choice
        description: Version type
        options: 
        - patch
        - minor
        - major
      
env:
  node_version: 22
  deployment_branch: main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  check-deployment-branch:
    name: Check deployment branch
    outputs:
      is_main: ${{ steps.check_branch.outputs.is_main }}
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Check deployment branch
      id: check_branch
      run: |
        if [ "${{ github.ref }}" != "refs/heads/${{ env.deployment_branch }}" ]; then
          echo "This workflow can only be run on the main branch."
          echo "is_main=false" >> $GITHUB_OUTPUT
          exit 1
        else
          echo "This workflow is running on the main branch."
          echo "is_main=true" >> $GITHUB_OUTPUT
        fi
  
  build-and-publish:
    name: Build and publish
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: check-deployment-branch

    permissions:
      contents: write
      packages: write
      pull-requests: write

    # only runs if on the 'main' branch
    if: needs.check-deployment-branch.outputs.is_main == 'true'
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js ${{ env.node_version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.node_version }}
        cache: 'npm'
        cache-dependency-path: package-lock.json
        registry-url: 'https://npm.pkg.github.com'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build

    - name: Setup git user info
      run: | 
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"   

    - name: Create version
      id: create_version
      run: npm run version:${{inputs.version}}
    
    - name: Publish
      run: npm run version:publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Merge main into dev with pull request
      id: merge_dev
      run: gh pr create --base dev --head main --title "Merge main into dev after release" --body "Merging main into dev" --assignee ${{ github.actor }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get package version
      id: package-version
      run: |
        VERSION=$(jq -r '.version' package.json)
        echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "Package version is: $VERSION"

    - name: Set job summary
      run: |
        echo "## Package Version" >> $GITHUB_STEP_SUMMARY
        echo "- Version: ${{ steps.package-version.outputs.PACKAGE_VERSION }}" >> $GITHUB_STEP_SUMMARY
