name: Build and deploy dev

on:
  push:
    branches: 
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build-and-publish:
    uses: jpbnetley/npm-version-release-action/.github/workflows/action.yml@main
    with:
      node_version: 22
      package_manager: 'npm'
      path_to_package_json: './package.json'
      path_to_package_lock: './package-lock.json'
      registry_url: 'https://npm.pkg.github.com'
      install_command: 'npm ci'
      build_command: 'npm run build'
      build_output_path: 'dist'
      deployment_branch_name: 'dev'
      version_command: 'npm run version:dev'
      publish_command: 'npm run version:publish:dev'
    secrets: inherit
