# This is a basic workflow to help you get started with Actions

name: Build and deploy dev

on:
  push:
    branches: 
      - dev

env:
  node_version: 22

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "install"
  
  build-and-publish:
    name: Build and publish
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js ${{ env.node_version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.node_version }}
        cache: 'npm'
        cache-dependency-path: package-lock.json
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build

    - name: Setup git user info
      run: | 
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"   

    - name: Create version
      id: create_version
      run: npm run version:dev
    
    - name: Publish
      run: npm run version:publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy
      if: github.ref == 'refs/heads/dev'
      run: |
        echo "Deploying to development environment..."
        # Add your deployment commands here